### ISSUE TITLE
General questions

### ISSUE THREAD

**Issue by halirutan** [corywalker/expreduce#111]
I'm watching this repo for a while with interest. What I'm missing is a Wiki page that explains the general goal of this project if there is one. Is it only for fun or are you planning to provide functionality that improves certain (small) parts of the core Mathematica language? It seems clear, that you are currently concentrating on term rewriting and pattern matching which is a good thing as it is the central part of the language. The major point regarding the core language I'm interested in is

**Are you trying to copy the behaviour of evaluation or do you try to provide a better/faster/more intuitive implementation?**

Several things come to mind here. For one, you might know that the [pattern specificity](https://mathematica.stackexchange.com/q/8619/187) is a particularly hard thing to tackle. In your implementation, this doesn't seem to handle this correctly at the moment which leads following unintuitive crash

```
f[1] = 1;
f[x_] := f[x - 1]*x

f[2]
```
In fact, above bug seems to be a deeper issue because even when you sort the `DownValues` by hand, the system crashes.

Furthermore, if you compare `ReplaceAll` and `Replace` there are crucial differences how expressions are walked and rules are applied. Additionally, do you plan to exclude useless features like the [implicit `Null` in sequences like `f[,]`](https://github.com/corywalker/expreduce/issues/106)? Other things like replacements of `Complex` (which is currently no atom in your implementation).

My viewpoint is that before any further features are added, the core functionality of patterns, replacements, `XXXValues`, etc needs a clear plan, must be thoroughly tested and profiled. I would find it extremely helpful for future visitors if you could provide your intentions.

**Comment by cekdahl** [comment]
For the `ReplaceAll` issue see #104.

**Comment by corywalker** [comment]
Thanks for the interest in the project. My hope for the project is that it allows for others to run their code in an open source environment that is efficient and reasonably feature complete. This and for others to be able to learn from the code of a developed term-rewrite system CAS to see how such a system would work. I would say the goal is neither the behavior of the evaluation nor prematurely optimizing aspects of the project.

The features that I add are project driven. A previous project was to support square free factorization. I've added that and any built-in functions or features of the evaluation that were necessary for that code.

Right now the goal is to support Rubi, which is the largest open source term-rewrite-based project I've seen, and will allow for people to use Albert's meticulously compiled set of integration rules from an open-source environment. Supporting this large project involves adding built-in functions here and there, making a small number of evaluation tweaks, and optimizations here and there. But the goal for the features I add is to support Rubi now. Since the project is large, by the end we see that we have complete evaluation and an efficient implementation.

As for the issues you mention:
Yes, the pattern specificity is a known issue. Right now it just treats the string length of the LHS as the specificity, which is surprisingly correct for many cases but fails for the single digit integer vs Blank case that you mention. Assigning to the DownValues directly does not change the downvalues, but will soon.

For the other issues, I haven't addressed these because the use cases I've wanted to support have not needed them.

**Comment by halirutan** [comment]
Thanks for your comment. Targeting RUBI is a nice goal. In the mean time we had a little [chat about Expreduce](https://chat.stackexchange.com/rooms/65967/expreduce), where I pointed out my concerns. Please don't feel offended! It's basically in no way critique on your specific project. Rather, there are quite some expert Mathematica users that see the quality of Mathematica decline for several years now. In the light of languages like Julia, that often reach C-like speed by using JIT compilation, it's hard to see the future of Mathematica being more than a prototyping/interactive tool with shiny features (which is fine in itself).

This is why many people keep an open eye on projects like yours and lookout for possible alternatives. Especially, for a core that doesn't provide any real features but is modern and fast enough to overcome the current shortcomings of Mathematica.
On the [Julia page](https://julialang.org/) there is the famous `fib` example where Mathematica is pretty slow in comparison. Keeping in mind that the double recursion of `fib` mainly reveals the pure speed of term rewriting without hard computation this is unfortunate.

```
fib[0] = 0;
fib[1] = 1;
fib[x_] := fib[x - 1] + fib[x - 2]

fib[30] //Timing
```

In your implementation we need to hack around the `DownValues` sorting issue and I acknowledge that there is surely some overhead because of this

``` 
fib[x_/;x==0]:=0
fib[x_/;x==1]:=1
fib[x_]:=fib[x-1]+fib[x-2]
```

Nevertheless, Expreduce is about 200x slower than Mathematica which didn't have a great performance to begin with. I'm not sure something fundamental like this can be fixed when the system is reasonably finished.

**Comment by corywalker** [comment]
Thanks for all the great commentary in both your comment and in the chat log. I do agree on all your points of Mathematica has some serious design issues. There are tons of dark corners as you and others mention. The built in library is massive with not much in the way of packaging and modularity. Also the core pattern matching is bulky with edge cases as well, which has been pointed out. I would completely eliminate many of the ways MMA allows for changing evaluation state, which would allow for a smaller core, less edge cases, and a greater possibility of supporting JIT. Finally one of the most frustrating aspects of MMA for me is the ability to have undefined functions called quietly and returning unevaluated. This is both a blessing and a curse for a symbolic language, but for MMA I think this is more often a curse.

I've been using Mathematica on a surface level for school / other work for years. Before that, various open source CAS's that did not cost as much. Mathematica always blew me away in the elegance of the system **at the surface level**. There are still some parts that continue to impress me at a deeper level, but there are some gross parts. When I embarked on this project, I had neither implemented a programming language, nor understood the dark corners of Mathematica syntax. Now that I have done both, I believe I can actually offer some useful thoughts on how to improve such a system. I learn by doing, so writing this project is the most effective way of accomplishing those two things. If there is ever a serious conversation about a modern language for a CAS, I would love to be a part of that discussion and I could probably offer some useful thoughts.

Regardless, the support for RUBI seems very close as of the last time I worked on the project. It would be a shame for this collection of rules to not have an open source option to run them.

BTW You're correct that the case you use in Expreduce definitely has some overhead. The Condition operation is heavyweight. Setting DownValues directly are supported very recently in my dev branch:

    DownValues[fib]={HoldPattern[fib[0]]->0,HoldPattern[fib[1]]->1,HoldPattern[fib[x_]]->fib[x-1]+fib[x-2]}

fib[20] has a timing of 60 seconds while in MMA I see 3. Honestly this is not that bad IMO considering I have not tried to optimize raw recursion speed yet. I'm fairly confident I could easily get it to be less than 10, perhaps even lower than 5. It's quite common to see speed improvements like this when optimizing for a new use case.

**Comment by cznic** [comment]
@corywalker 

> fib[20] has a timing of 60 seconds while in MMA I see 3.

I'm probably misunderstanding something, but even the 3 seconds look like eternity to me. I guess with memoizing fib[20] should evaluate in milliseconds.

----

OT: cznic/wl#12 is ready for review.

**Comment by cekdahl** [comment]
> I'm probably misunderstanding something, but even the 3 seconds look like eternity to me. I guess with memoizing fib[20] should evaluate in milliseconds.

I'm seeing 0.026 seconds for `fib[20]` in Mathematica without memoization. The slower definition that makes use of conditions (`/;`) takes 3.8 seconds for `fib[30]`.

**Comment by halirutan** [comment]
It seems my computer is a bit different. I cannot test the `DownValues[fib]` hack, because somehow the downvalues are not assigned to `fib` when I do this. Nevertheless, `fib[30]` needs 2.9 seconds (it's fib[**30**]).

@cznic Well, don't forget that it's interpreted and that `fib[30]` needs 1.3 million evaluations of fib.

@corywalker Would there be any chance that you create a Gitter chat room for your project?

**Comment by cznic** [comment]
@halirutan As I told, I'm probably misunderstamding something, but it still seems to me that fib[30] needs to be evaluated (with memoization) only 28 times (fib[0] and fib[1] are known already), so yes, I think it can be done in milliseconds by an interpretter. What am I missing?

**Comment by cznic** [comment]
@corywalker @halirutan As a proof of concept here's a tiny interpretter 

```go
package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"strconv"
	"time"
)

type def struct {
	arg ast.Expr
	rhs ast.Expr
}

type key struct {
	name string
	arg  int
}

var defs = map[string][]*def{}

func main() {
	node, err := parser.ParseExpr("func() { fib(0) = 0; fib(1) = 1; fib(x) = fib(x-1)+fib(x-2) }")
	if err != nil {
		panic(err)
	}
	for _, v := range node.(*ast.FuncLit).Body.List {
		as := v.(*ast.AssignStmt)
		f := as.Lhs[0].(*ast.CallExpr)
		name := f.Fun.(*ast.Ident).Name
		defs[name] = append(defs[name], &def{f.Args[0].(ast.Expr), as.Rhs[0]})
	}
	expr, err := parser.ParseExpr("fib(30)")
	if err != nil {
		panic(err)
	}
	t0 := time.Now()
	fmt.Println(eval(map[key]int{}, nil, expr))
	fmt.Println(time.Since(t0))
}

func atoi(s string) int {
	v, err := strconv.Atoi(s)
	if err != nil {
		panic(err)
	}
	return v
}

func eval(mem map[key]int, vars map[string]int, expr ast.Expr) (y int) {
	switch x := expr.(type) {
	case *ast.BasicLit:
		return atoi(x.Value)
	case *ast.BinaryExpr:
		a := eval(mem, vars, x.X)
		b := eval(mem, vars, x.Y)
		switch x.Op {
		case token.ADD:
			return a + b
		case token.SUB:
			return a - b
		}
	case *ast.CallExpr:
		name := x.Fun.(*ast.Ident).Name
		arg := eval(mem, vars, x.Args[0])
		k := key{name, arg}
		if v, ok := mem[k]; ok {
			return v
		}
		defer func() {
			mem[k] = y
		}()
		for _, v := range defs[name] {
			switch param := v.arg.(type) {
			case *ast.BasicLit:
				if param := atoi(param.Value); param == arg {
					return eval(mem, vars, v.rhs)
				}
			case *ast.Ident:
				return eval(mem, map[string]int{param.Name: arg}, v.rhs)
			}
		}
	case *ast.Ident:
		if v, ok := vars[x.Name]; ok {
			return v
		}
	}
	panic("internal error")
}
```
[playground](https://play.golang.org/p/h0eNl3tjyG)

Time does not change in the playground, running it locally I'm getting

```bash
jnml@4670:~/src/tmp$ go run main.go 
832040
60.012µs
jnml@4670:~/src/tmp$ 
```

Of course, its performance cannot be faily compared to the performance of a real term rewriting system like expreduce, but even at, say 1000 times overhead, it'll be only about 60 milliseconds.

**Comment by corywalker** [comment]
@cznic, @cekdahl,

We intentionally avoid memoization for this test. It's a stress test for recursive efficiency. It's a naïve implementation for the sake of a benchmark.

Also, before I had a typo. I meant to say fib[30] instead of fib[20]. fib[30] does take about 3 seconds on MMA and Expreduce is an order of magnitude slower for raw recursion.

I've created #113 to track this performance issue, and I've started https://gitter.im/expreduce for further comments :)

**Comment by sblom** [comment]
@corywalker, I'm pretty excited to see someone working on a project like this. I'm coming from a significantly different perspective than @halirutan represented above. My interest in an open-source implementation of the Wolfram language is not as an alternative to Mathematica per se. It's, rather, as a complement to Mathematica and the WRI-official implementations of the Wolfram Language. Y'see one of the areas where I feel Mathematica is lagging the most compared to its modern competitors is in the area of sharing packages and community-based prototyping and experimentation.

The Mathematica community is way too economically exclusive (either have $300+ lying around as an individual, or be active at an institution with a $NNk+ software budget lying around) for us to reach the kind of open source critical mass of tinkering, experimenting, sharing, riffing, deriving, etc. that communities with low entry barriers have.

The way I see things, there is _tremendous_ value in WRI continuing to produce Mathematica with its amazing UI, Wolfram Alpha integration, tons of incredibly powerful computation libraries to enable fast starts with complex computations such as machine learning, and so on. There is no question that these are the parts of Mathematica that attract my $$$, and that attract institutional $$$$$, and there's no question that they can continue working on closed, commercial implementations of those parts plus interesting web scale services such as the Wolfram Cloud, and live on as a software industry great for many decades to come.

Meanwhile, those of us who want to actually build interesting software are nearly universally forced to go where there are developer communities: Python, Julia, even Ruby or Node. One of the best ways for Mathematica to capture some of that attention would be for a community-based implementation of the Wolfram Language Core to be available for free and run almost anywhere. It would be important to agree where the cut line is for "Core" vs not, but it needs to be a broad enough core that almost any kind of interesting packages can be built to run on it, importantly, with high enough Mathematica interoperability that pretty much 100% of things that can run in it can run in Mathematica. The converse (arbitrary Mathematica code being able to run in the open Core) is less important, but not without value.

Essentially, if the community had a broad enough Core that package authors could target it and know that their packages will be useful to open source users as well as the more (initially) numerous Mathematica users, they would have the ability to dig in and start contributing.

I honestly believe that WRI would be well-served to package up such a core and seed a community with it, possibly even largely separating the language team from the various library teams, because I believe that will be the only real way to get Mathematica out from its (very profitable) relative obscurity and into the hands of the "I want to use cool tools" open source crowd.

I will personally celebrate the day that Mathematica meets the "free compiler" test and I can use it to solve Google Code Jam competition problems!

Looking forward to lurking, and maybe contributing someday, @corywalker!

**Comment by corywalker** [comment]
@sblom, thanks for your thoughts. I'm always a proponent of more open software ecosystems, and having the core you mention could allow for more sharing and collaboration of code. The idea here is that the term rewriting engine is mostly complete, and the vast majority of the functionality is implemented as Mathematica rules. In this way, the core can easily be expanded by anyone who wants to contribute.
