### ISSUE TITLE
More detailed development section in readme

### ISSUE THREAD

**Issue by cekdahl** [corywalker/expreduce#95]
I'm new to Go and I'd appreciate more detail in the "development" section in the readme. I started by cloning the repository to my src directory. When I first wanted to get it to compile I had to retrieve the packages, `go generate` wouldn't do this for me, the only way I found was:

    go get github.com/corywalker/expreduce

which installed expreduce in a separate directory and as a side-effect downloaded the packages. Is this how it should be done?

After this I could run the code using `go run expreduce.go`, but I soon realized that any changes that I made to the code weren't being included. I think the problem is the line

    "github.com/corywalker/expreduce/expreduce"

which imports the version of the package that's online I guess. So I tried changing it to just `expreduce` to get the local version – that didn't work:

    import "expreduce" is a program, not an importable package

If you could please clarify how I should set it up so that I can develop the code and add new features, I'd be very grateful! Thanks!

**Comment by cznic** [comment]
Start by something like

```bash
$ go get github.com/corywalker/expreduce
$ cd $GOPATH/src/github.com/corywalker/expreduce
$ git checkout -b myexperiment
... make your changes
$ go install
$ expreduce # should be in your $PATH with the usual setup of things
```

If you want to change things that require regenerating sources

```bash
$ cd $GOPATH/src/github.com/corywalker/expreduce
$ go generate ./...
$ go install
$ expreduce
```

`go generate` will probably complain about missing programs, install them once by, for example, `go get github.com/cznic/goyacc` etc.

**Comment by corywalker** [comment]
cznic's comments should get you on the right track. I tend to use "go run expreduce.go" as you do instead of "go install", but that's just a matter of preference. A few guidelines:

go run expreduce.go will pick up any changes you make in the .go files. Any changes you make in the .m files, you will need to run the "go generate ./...". This is because the contents of the .m files are essentially copied into a string representation in the automatically generated "resources.go".

If you made any changes to the .m files, then simply running "go run expreduce.go" would not pick up the changes and could explain your issue.

I'll probably update the README with this info soon.

**Comment by cekdahl** [comment]
It works now, thank you all.
